@startuml

actor Admin
participant Controller
participant UserRepository

Admin -> Controller : GET /users
Controller -> UserRepository : Demande la liste des utilisateurs
UserRepository -> Controller : Récupére la liste des utilisateurs
Controller -> Admin : Retourne la liste des users
@enduml
