@startuml

actor User
participant Controller
participant UserRepository

User -> Controller : GET /users
Controller -> UserRepository : Demande la liste des utilisateurs
UserRepository -> Controller : Récupére la liste des utilisateurs
Controller -> User : Retourne la liste des users
@enduml
